feat: allow hooks for global and bulk smart action
ForestAdmin/forest-express-mongoose pull request #622
Opened 2021-07-06 14:58 UTC by arnaud-moncel

## Pull Request checklist:

- [X] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Create automatic tests
- [X] Test manually the implemented changes
- [X] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code
- [X] If needed, Types have been updated

2021-07-07 08:10 UTC, SteveBunlon approved these changes
Nice thanks for the update 😄 

Just one thing to fix and you can 🚀

2021-07-07 08:10 UTC, SteveBunlon commented on types/index.d.ts
> +    type: string,
```suggestion
    type: 'custom-action-requests',
```

2021-07-07 08:14 UTC, SteveBunlon requested changes

2021-07-07 08:14 UTC, SteveBunlon commented on types/index.d.ts
> +  (context: { fields: SmartActionLoadHookField[], request: SmartActionHookRequest }): SmartActionLoadHookField[]
Actually, the T generic type is not used anymore. If we don't provide any record to the user, you can remove it.

2021-07-07 08:14 UTC, SteveBunlon commented on types/index.d.ts
> +  (context: { fields: SmartActionChangeHookField[], changedField: SmartActionChangeHookField, request: SmartActionHookRequest }): SmartActionChangeHookField[]
Actually, the T generic type is not used anymore. If we don't provide any record to the user, you can remove it.

2021-07-07 08:16 UTC, arnaud-moncel commented on types/index.d.ts
> +    type: string,
I don't know it is possible 😱  thanks 😀

2021-07-07 08:21 UTC, SteveBunlon requested changes

2021-07-07 08:21 UTC, SteveBunlon commented on types/index.d.ts
> +  data: {
The `values` attribute is not present anymore ?

2021-07-07 08:21 UTC, SteveBunlon commented on types/index.d.ts
> +  getIdsFromRequest(request: ForestRequest): Promise<string[]>;
[THINKING] Couldn't it be the same as SmartActionHookRequest ?

2021-07-07 09:35 UTC, SteveBunlon submitted a review, later dismissed
🔥 🔥 🔥 🔥 🔥 🔥 🔥

2021-07-08 15:43 UTC, SteveBunlon approved these changes
🏌️

2021-07-09 07:38 UTC, merged