fix(smart field): fix filter on smart reference
ForestAdmin/forest-express-mongoose pull request #669
Opened 2021-09-14 09:07 UTC by VincentMolinie

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2021-09-14 10:30 UTC, romain-gilliotte requested changes

2021-09-14 10:30 UTC, romain-gilliotte commented on package.json
> +    "forest-express": "9.2.4",
This is one of the bad versions of forest-express.
We need to wait and change this

2021-09-29 13:09 UTC, adriguy approved these changes
Filtering on smart reference was already working... but still with this refacto 👌 
(One tiny comment and a rebase to do)

2021-09-29 13:09 UTC, adriguy commented on test/tests/services/filters-parser.test.js
> +    it('with an embedded field', async () => {
Bad description

2021-09-29 13:19 UTC, adriguy approved these changes

2021-09-29 13:55 UTC, merged